#!/bin/bash
# build.sh — Ultra-minimal LLVM+Clang build for PerfSanitizer development
#
# Usage: ./build.sh [--llvm-only | --plugin-only | --all | --dogfood | --docker]

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
LLVM_ROOT="$(dirname "$SCRIPT_DIR")"
LLVM_BUILD="$LLVM_ROOT/build-perfsanitizer"
PLUGIN_BUILD="$SCRIPT_DIR/build"
NPROC=$(nproc 2>/dev/null || sysctl -n hw.ncpu 2>/dev/null || echo 4)

MODE="${1:---all}"

build_llvm() {
  echo "=== Building ultra-minimal LLVM + Clang + LLD ==="
  echo "  Build type:   MinSizeRel"
  echo "  Compiler:     $(clang++ --version 2>/dev/null | head -1 || c++ --version 2>/dev/null | head -1)"
  echo "  ccache:       $(command -v ccache >/dev/null && echo enabled || echo not found)"
  echo "  Parallelism:  $NPROC"
  echo "  Tools:        clang driver, opt, llvm-config (everything else OFF)"

  cmake -G Ninja -S "$LLVM_ROOT/llvm" -B "$LLVM_BUILD" \
    -DCMAKE_BUILD_TYPE=MinSizeRel \
    -DCMAKE_C_COMPILER=clang \
    -DCMAKE_CXX_COMPILER=clang++ \
    \
    -DLLVM_ENABLE_PROJECTS="clang;lld" \
    -DLLVM_TARGETS_TO_BUILD=Native \
    -DLLVM_USE_LINKER=lld \
    -DLLVM_CCACHE_BUILD=ON \
    -DLLVM_PARALLEL_LINK_JOBS=2 \
    \
    -DLLVM_ENABLE_ASSERTIONS=OFF \
    -DLLVM_ENABLE_BACKTRACES=OFF \
    -DLLVM_ENABLE_CRASH_OVERRIDES=OFF \
    -DLLVM_ENABLE_LIBEDIT=OFF \
    -DLLVM_ENABLE_LIBPFM=OFF \
    -DLLVM_ENABLE_TELEMETRY=OFF \
    -DLLVM_ENABLE_UNWIND_TABLES=OFF \
    -DLLVM_ENABLE_BINDINGS=OFF \
    -DLLVM_ENABLE_OCAMLDOC=OFF \
    -DLLVM_ENABLE_Z3_SOLVER=OFF \
    -DLLVM_ENABLE_TERMINFO=OFF \
    -DLLVM_ENABLE_ZLIB=OFF \
    -DLLVM_ENABLE_ZSTD=OFF \
    -DLLVM_ENABLE_ONDISK_CAS=OFF \
    -DLLVM_ENABLE_PLUGINS=ON \
    -DLLVM_ENABLE_THREADS=ON \
    -DLLVM_ENABLE_PIC=ON \
    -DLLVM_APPEND_VC_REV=OFF \
    \
    -DLLVM_INCLUDE_TESTS=OFF \
    -DLLVM_INCLUDE_BENCHMARKS=OFF \
    -DLLVM_INCLUDE_EXAMPLES=OFF \
    -DLLVM_INCLUDE_DOCS=OFF \
    -DLLVM_INCLUDE_RUNTIMES=OFF \
    -DLLVM_INCLUDE_TOOLS=ON \
    -DLLVM_INCLUDE_UTILS=ON \
    -DLLVM_BUILD_TOOLS=OFF \
    -DLLVM_BUILD_UTILS=OFF \
    -DLLVM_BUILD_RUNTIME=OFF \
    -DLLVM_BUILD_RUNTIMES=OFF \
    \
    -DCLANG_ENABLE_STATIC_ANALYZER=OFF \
    -DCLANG_ENABLE_LIBXML2=OFF \
    -DCLANG_BUILD_TOOLS=OFF \
    -DCLANG_INSTALL_HMAPTOOL=OFF \
    -DCLANG_PLUGIN_SUPPORT=ON \
    \
    -DLLD_BUILD_TOOLS=ON \
    \
    -DLLVM_TOOL_OPT_BUILD=ON \
    -DLLVM_TOOL_LLVM_CONFIG_BUILD=ON \
    -DLLVM_TOOL_LLC_BUILD=OFF \
    -DLLVM_TOOL_LLI_BUILD=OFF \
    -DLLVM_TOOL_LLVM_AR_BUILD=OFF \
    -DLLVM_TOOL_LLVM_AS_BUILD=OFF \
    -DLLVM_TOOL_LLVM_AS_FUZZER_BUILD=OFF \
    -DLLVM_TOOL_LLVM_BCANALYZER_BUILD=OFF \
    -DLLVM_TOOL_LLVM_CAS_BUILD=OFF \
    -DLLVM_TOOL_LLVM_CAT_BUILD=OFF \
    -DLLVM_TOOL_LLVM_CFI_VERIFY_BUILD=OFF \
    -DLLVM_TOOL_LLVM_CGDATA_BUILD=OFF \
    -DLLVM_TOOL_LLVM_COV_BUILD=OFF \
    -DLLVM_TOOL_LLVM_C_TEST_BUILD=OFF \
    -DLLVM_TOOL_LLVM_CTXPROF_UTIL_BUILD=OFF \
    -DLLVM_TOOL_LLVM_CVTRES_BUILD=OFF \
    -DLLVM_TOOL_LLVM_CXXDUMP_BUILD=OFF \
    -DLLVM_TOOL_LLVM_CXXFILT_BUILD=OFF \
    -DLLVM_TOOL_LLVM_CXXMAP_BUILD=OFF \
    -DLLVM_TOOL_LLVM_DEBUGINFO_ANALYZER_BUILD=OFF \
    -DLLVM_TOOL_LLVM_DEBUGINFOD_BUILD=OFF \
    -DLLVM_TOOL_LLVM_DEBUGINFOD_FIND_BUILD=OFF \
    -DLLVM_TOOL_LLVM_DIFF_BUILD=OFF \
    -DLLVM_TOOL_LLVM_DIS_BUILD=OFF \
    -DLLVM_TOOL_LLVM_DIS_FUZZER_BUILD=OFF \
    -DLLVM_TOOL_LLVM_DLANG_DEMANGLE_FUZZER_BUILD=OFF \
    -DLLVM_TOOL_LLVM_DWARFDUMP_BUILD=OFF \
    -DLLVM_TOOL_LLVM_DWARFUTIL_BUILD=OFF \
    -DLLVM_TOOL_LLVM_DWP_BUILD=OFF \
    -DLLVM_TOOL_LLVM_EXEGESIS_BUILD=OFF \
    -DLLVM_TOOL_LLVM_EXTRACT_BUILD=OFF \
    -DLLVM_TOOL_LLVM_GPU_LOADER_BUILD=OFF \
    -DLLVM_TOOL_LLVM_GSYMUTIL_BUILD=OFF \
    -DLLVM_TOOL_LLVM_IFS_BUILD=OFF \
    -DLLVM_TOOL_LLVM_IR2VEC_BUILD=OFF \
    -DLLVM_TOOL_LLVM_ISEL_FUZZER_BUILD=OFF \
    -DLLVM_TOOL_LLVM_ITANIUM_DEMANGLE_FUZZER_BUILD=OFF \
    -DLLVM_TOOL_LLVM_JITLINK_BUILD=OFF \
    -DLLVM_TOOL_LLVM_JITLISTENER_BUILD=OFF \
    -DLLVM_TOOL_LLVM_LIBTOOL_DARWIN_BUILD=OFF \
    -DLLVM_TOOL_LLVM_LINK_BUILD=OFF \
    -DLLVM_TOOL_LLVM_LIPO_BUILD=OFF \
    -DLLVM_TOOL_LLVM_LTO_BUILD=OFF \
    -DLLVM_TOOL_LLVM_LTO2_BUILD=OFF \
    -DLLVM_TOOL_LLVM_MC_BUILD=OFF \
    -DLLVM_TOOL_LLVM_MC_ASSEMBLE_FUZZER_BUILD=OFF \
    -DLLVM_TOOL_LLVM_MC_DISASSEMBLE_FUZZER_BUILD=OFF \
    -DLLVM_TOOL_LLVM_MCA_BUILD=OFF \
    -DLLVM_TOOL_LLVM_MICROSOFT_DEMANGLE_FUZZER_BUILD=OFF \
    -DLLVM_TOOL_LLVM_ML_BUILD=OFF \
    -DLLVM_TOOL_LLVM_MODEXTRACT_BUILD=OFF \
    -DLLVM_TOOL_LLVM_MT_BUILD=OFF \
    -DLLVM_TOOL_LLVM_NM_BUILD=OFF \
    -DLLVM_TOOL_LLVM_OBJCOPY_BUILD=OFF \
    -DLLVM_TOOL_LLVM_OBJDUMP_BUILD=OFF \
    -DLLVM_TOOL_LLVM_OFFLOAD_BINARY_BUILD=OFF \
    -DLLVM_TOOL_LLVM_OFFLOAD_WRAPPER_BUILD=OFF \
    -DLLVM_TOOL_LLVM_OPT_FUZZER_BUILD=OFF \
    -DLLVM_TOOL_LLVM_OPT_REPORT_BUILD=OFF \
    -DLLVM_TOOL_LLVM_PDBUTIL_BUILD=OFF \
    -DLLVM_TOOL_LLVM_PROFDATA_BUILD=OFF \
    -DLLVM_TOOL_LLVM_PROFGEN_BUILD=OFF \
    -DLLVM_TOOL_LLVM_RC_BUILD=OFF \
    -DLLVM_TOOL_LLVM_READOBJ_BUILD=OFF \
    -DLLVM_TOOL_LLVM_READTAPI_BUILD=OFF \
    -DLLVM_TOOL_LLVM_REDUCE_BUILD=OFF \
    -DLLVM_TOOL_LLVM_REMARKUTIL_BUILD=OFF \
    -DLLVM_TOOL_LLVM_RTDYLD_BUILD=OFF \
    -DLLVM_TOOL_LLVM_RUST_DEMANGLE_FUZZER_BUILD=OFF \
    -DLLVM_TOOL_LLVM_SHLIB_BUILD=OFF \
    -DLLVM_TOOL_LLVM_SIM_BUILD=OFF \
    -DLLVM_TOOL_LLVM_SIZE_BUILD=OFF \
    -DLLVM_TOOL_LLVM_SPECIAL_CASE_LIST_FUZZER_BUILD=OFF \
    -DLLVM_TOOL_LLVM_SPLIT_BUILD=OFF \
    -DLLVM_TOOL_LLVM_STRESS_BUILD=OFF \
    -DLLVM_TOOL_LLVM_STRINGS_BUILD=OFF \
    -DLLVM_TOOL_LLVM_SYMBOLIZER_BUILD=OFF \
    -DLLVM_TOOL_LLVM_TLI_CHECKER_BUILD=OFF \
    -DLLVM_TOOL_LLVM_UNDNAME_BUILD=OFF \
    -DLLVM_TOOL_LLVM_XRAY_BUILD=OFF \
    -DLLVM_TOOL_LLVM_YAML_NUMERIC_PARSER_FUZZER_BUILD=OFF \
    -DLLVM_TOOL_LLVM_YAML_PARSER_FUZZER_BUILD=OFF \
    -DLLVM_TOOL_LTO_BUILD=OFF \
    -DLLVM_TOOL_OBJ2YAML_BUILD=OFF \
    -DLLVM_TOOL_OPT_VIEWER_BUILD=OFF \
    -DLLVM_TOOL_REDUCE_CHUNK_LIST_BUILD=OFF \
    -DLLVM_TOOL_REMARKS_SHLIB_BUILD=OFF \
    -DLLVM_TOOL_SANCOV_BUILD=OFF \
    -DLLVM_TOOL_SANSTATS_BUILD=OFF \
    -DLLVM_TOOL_SPIRV_TOOLS_BUILD=OFF \
    -DLLVM_TOOL_VERIFY_USELISTORDER_BUILD=OFF \
    -DLLVM_TOOL_VFABI_DEMANGLE_FUZZER_BUILD=OFF \
    -DLLVM_TOOL_XCODE_TOOLCHAIN_BUILD=OFF \
    -DLLVM_TOOL_YAML2OBJ_BUILD=OFF \
    -DLLVM_TOOL_DXIL_DIS_BUILD=OFF \
    -DLLVM_TOOL_GOLD_BUILD=OFF \
    -DLLVM_TOOL_LLUBI_BUILD=OFF \
    -DLLVM_TOOL_DSYMUTIL_BUILD=OFF \
    \
    -DCLANG_TOOL_DRIVER_BUILD=ON \
    -DCLANG_TOOL_APINOTES_TEST_BUILD=OFF \
    -DCLANG_TOOL_C_INDEX_TEST_BUILD=OFF \
    -DCLANG_TOOL_CIR_LSP_SERVER_BUILD=OFF \
    -DCLANG_TOOL_CIR_OPT_BUILD=OFF \
    -DCLANG_TOOL_CIR_TRANSLATE_BUILD=OFF \
    -DCLANG_TOOL_CLANG_CHECK_BUILD=OFF \
    -DCLANG_TOOL_CLANG_DIFF_BUILD=OFF \
    -DCLANG_TOOL_CLANG_EXTDEF_MAPPING_BUILD=OFF \
    -DCLANG_TOOL_CLANG_FORMAT_BUILD=OFF \
    -DCLANG_TOOL_CLANG_FUZZER_BUILD=OFF \
    -DCLANG_TOOL_CLANG_IMPORT_TEST_BUILD=OFF \
    -DCLANG_TOOL_CLANG_INSTALLAPI_BUILD=OFF \
    -DCLANG_TOOL_CLANG_LINKER_WRAPPER_BUILD=OFF \
    -DCLANG_TOOL_CLANG_NVLINK_WRAPPER_BUILD=OFF \
    -DCLANG_TOOL_CLANG_OFFLOAD_BUNDLER_BUILD=OFF \
    -DCLANG_TOOL_CLANG_OFFLOAD_PACKAGER_BUILD=OFF \
    -DCLANG_TOOL_CLANG_REFACTOR_BUILD=OFF \
    -DCLANG_TOOL_CLANG_REPL_BUILD=OFF \
    -DCLANG_TOOL_CLANG_SCAN_DEPS_BUILD=OFF \
    -DCLANG_TOOL_CLANG_SHLIB_BUILD=OFF \
    -DCLANG_TOOL_CLANG_SSAF_FORMAT_BUILD=OFF \
    -DCLANG_TOOL_CLANG_SSAF_LINKER_BUILD=OFF \
    -DCLANG_TOOL_CLANG_SYCL_LINKER_BUILD=OFF \
    -DCLANG_TOOL_DIAGTOOL_BUILD=OFF \
    -DCLANG_TOOL_DICTIONARY_BUILD=OFF \
    -DCLANG_TOOL_HANDLE_CXX_BUILD=OFF \
    -DCLANG_TOOL_HANDLE_LLVM_BUILD=OFF \
    -DCLANG_TOOL_LIBCLANG_BUILD=OFF \
    -DCLANG_TOOL_OFFLOAD_ARCH_BUILD=OFF \
    -DCLANG_TOOL_SCAN_BUILD_BUILD=OFF \
    -DCLANG_TOOL_SCAN_BUILD_PY_BUILD=OFF \
    -DCLANG_TOOL_SCAN_VIEW_BUILD=OFF

  cmake --build "$LLVM_BUILD" -- -j"$NPROC"
  echo "=== LLVM build complete ==="
  echo "  clang: $LLVM_BUILD/bin/clang"
  echo "  opt:   $LLVM_BUILD/bin/opt"
}

build_plugin() {
  echo "=== Building PerfSanitizer plugin ==="

  if [ ! -d "$LLVM_BUILD" ]; then
    echo "ERROR: LLVM build not found at $LLVM_BUILD"
    echo "Run: $0 --llvm-only first"
    exit 1
  fi

  LLVM_DIR="$LLVM_BUILD/lib/cmake/llvm"
  CLANG_DIR="$LLVM_BUILD/lib/cmake/clang"

  cmake -G Ninja -S "$SCRIPT_DIR" -B "$PLUGIN_BUILD" \
    -DCMAKE_BUILD_TYPE=MinSizeRel \
    -DLLVM_DIR="$LLVM_DIR" \
    -DClang_DIR="$CLANG_DIR" \
    -DCMAKE_CXX_COMPILER_LAUNCHER=ccache

  cmake --build "$PLUGIN_BUILD" -- -j"$NPROC"

  PLUGIN_PATH=$(find "$PLUGIN_BUILD" -name 'libPerfSanitizer*' -o -name 'PerfSanitizer*' | head -1)
  echo "=== Plugin built: $PLUGIN_PATH ==="
  echo ""
  echo "  # Test on demo:"
  echo "  $LLVM_BUILD/bin/clang++ -fplugin=$PLUGIN_PATH -O2 -c $SCRIPT_DIR/tools/demo.cpp"
}

dogfood() {
  echo "=== Dogfooding: Compiling LLVM/Clang with PerfSanitizer ==="
  PLUGIN_PATH=$(find "$PLUGIN_BUILD" -name 'libPerfSanitizer*' -o -name 'PerfSanitizer*' | head -1)

  if [ -z "$PLUGIN_PATH" ]; then
    echo "ERROR: Plugin not found. Run: $0 --all first"
    exit 1
  fi

  DOGFOOD_BUILD="$LLVM_ROOT/build-dogfood"

  cmake -G Ninja -S "$LLVM_ROOT/llvm" -B "$DOGFOOD_BUILD" \
    -DCMAKE_BUILD_TYPE=MinSizeRel \
    -DLLVM_ENABLE_PROJECTS="clang" \
    -DLLVM_TARGETS_TO_BUILD=Native \
    -DLLVM_USE_LINKER=lld \
    -DLLVM_CCACHE_BUILD=ON \
    -DLLVM_PARALLEL_LINK_JOBS=2 \
    -DLLVM_INCLUDE_TESTS=OFF \
    -DLLVM_INCLUDE_BENCHMARKS=OFF \
    -DLLVM_INCLUDE_EXAMPLES=OFF \
    -DLLVM_INCLUDE_DOCS=OFF \
    -DCMAKE_C_COMPILER="$LLVM_BUILD/bin/clang" \
    -DCMAKE_CXX_COMPILER="$LLVM_BUILD/bin/clang++" \
    -DCMAKE_C_FLAGS="-fplugin=$PLUGIN_PATH" \
    -DCMAKE_CXX_FLAGS="-fplugin=$PLUGIN_PATH"

  echo "Dogfood configured. Run:"
  echo "  cmake --build $DOGFOOD_BUILD -- -j$NPROC 2>&1 | tee dogfood_report.txt"
}

build_docker() {
  echo "=== Building PerfSanitizer in Chimera Linux Docker ==="
  cd "$LLVM_ROOT"
  docker build -f perfsanitizer/Dockerfile -t perfsanitizer .
  echo ""
  echo "=== Done. Run with: ==="
  echo "  docker run -it -v \$(pwd):/work perfsanitizer"
}

case "$MODE" in
  --llvm-only)   build_llvm ;;
  --plugin-only) build_plugin ;;
  --all)         build_llvm; build_plugin ;;
  --dogfood)     dogfood ;;
  --docker)      build_docker ;;
  *)
    echo "Usage: $0 [--llvm-only | --plugin-only | --all | --dogfood | --docker]"
    exit 1
    ;;
esac
